const launchToken=new URLSearchParams(location.hash.slice(1)).get('token');
if(launchToken){
  sessionStorage.setItem('marginalia-session-token',launchToken);
  document.cookie=`marginalia_session_${location.port}=${encodeURIComponent(launchToken)}; SameSite=Strict; Path=/`;
  history.replaceState(null,'',location.pathname+location.search);
}
const sessionToken=sessionStorage.getItem('marginalia-session-token')||'';
const nativeFetch=window.fetch.bind(window);
window.fetch=(input,init={})=>{
  const target=new URL(input instanceof Request?input.url:String(input),location.href);
  if(target.origin!==location.origin||!sessionToken)return nativeFetch(input,init);
  const headers=new Headers(input instanceof Request?input.headers:undefined);
  new Headers(init.headers||{}).forEach((value,key)=>headers.set(key,value));
  headers.set('X-Marginalia-Token',sessionToken);
  return input instanceof Request
    ? nativeFetch(new Request(input,{...init,headers}))
    : nativeFetch(input,{...init,headers});
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let scope='all', retrievalMethod=localStorage.getItem('marginalia-retrieval-method')||'hybrid', progressTimer=null, answerProgressTimer=null, progressStartedAt=0, answerProgressStartedAt=0, progressValue=0, answerProgressValue=0, activeRequest=null, progressPhase='idle';
if(!['bm25','semantic','hybrid'].includes(retrievalMethod))retrievalMethod='hybrid';
let embeddingModel=localStorage.getItem('marginalia-embedding-model')||'qwen3-embedding:0.6b';
let answerModel=localStorage.getItem('marginalia-answer-model')||'gemma4:12b';
let resultState={query:'',scope:'all',method:'hybrid',embeddingModel,exact:false,generateAnswer:true,filters:{},results:[],hasMore:false,loading:false};
const expandedGroups=new Set(),publicationMatches=new Map();
let readerState=null,answerSources=[],answerEvidence=[];
let historyEntries=[],currentHistoryId=null,currentAnswerText='',currentAnswerMetrics=null,historySourceCurrent=true;
let contextRequest=null,contextSequence=0;
let matchSequence=0;const matchRegistry=new Map();
const labels={all:'everything in Zotero and Obsidian',annotations:'my annotations only',documents:'full document text',metadata:'titles and metadata',notes:'Zotero Notes',obsidian:'Obsidian Notes'};
const retrievalLabels={bm25:'BM25 · words',semantic:'Embeddings · meaning',hybrid:'Hybrid · BM25 + embeddings'};
const embeddingLabels=new Proxy({'qwen3-embedding:0.6b':'Qwen3 0.6B','qwen3-embedding:8b':'Qwen3 8B'},{get:(labels,model)=>labels[model]||String(model)});
const embeddingLabel=model=>embeddingLabels[model]||model;
let llmState=null;
const filterIds=['published-from','published-to','added-from','added-to'];
const folderState={zotero:{entries:[],excluded:new Set()},obsidian:{entries:[],excluded:new Set()}};
const folderStorage=source=>`marginalia-${source}-excluded-folders`;
function selectedFolders(source){const state=folderState[source];return state.excluded.size?state.entries.filter(entry=>!state.excluded.has(entry.key)).map(entry=>entry.key):null}
function currentFilters(){return{zotero_collections:selectedFolders('zotero'),obsidian_folders:selectedFolders('obsidian'),published_from:$('#published-from')?.value||'',published_to:$('#published-to')?.value||'',added_from:$('#added-from')?.value||'',added_to:$('#added-to')?.value||''}}
function filterCount(filters=currentFilters()){return Object.entries(filters).filter(([key,value])=>Array.isArray(value)?true:!!value).length}
function filterParams(filters=currentFilters()){const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(Array.isArray(value))params.set(key,JSON.stringify(value));else if(value)params.set(key,value)});return params.toString()}
function updateFilterBadge(){const count=filterCount();$('#advanced-count').textContent=count||'';$('#advanced-toggle').classList.toggle('active',!!count)}
function setFolderSelection(source,selected){const state=folderState[source];state.excluded.clear();if(Array.isArray(selected)){const allowed=new Set(selected.map(String));state.entries.forEach(entry=>{if(!allowed.has(entry.key))state.excluded.add(entry.key)})}persistFolders(source);renderFolderOptions(source)}
function setFilters(filters={}){setFolderSelection('zotero',filters.zotero_collections??null);setFolderSelection('obsidian',filters.obsidian_folders??null);$('#published-from').value=filters.published_from||'';$('#published-to').value=filters.published_to||'';$('#added-from').value=filters.added_from||'';$('#added-to').value=filters.added_to||'';updateFilterBadge()}
function validFilters(){for(const [from,to] of [['published-from','published-to'],['added-from','added-to']]){const first=$('#'+from),last=$('#'+to);first.setCustomValidity(first.value&&last.value&&first.value>last.value?'The start date must be before the end date.':'');if(!first.reportValidity())return false}return true}
function persistedExcluded(source){try{return new Set(JSON.parse(localStorage.getItem(folderStorage(source))||'[]').map(String))}catch{return new Set()}}
function persistFolders(source){localStorage.setItem(folderStorage(source),JSON.stringify([...folderState[source].excluded]));updateFilterBadge()}
function folderDescendants(source,key){const entries=folderState[source].entries;if(source==='obsidian'){if(!key)return entries.filter(entry=>!entry.key);return entries.filter(entry=>entry.key===key||entry.key.startsWith(key+'/'))}const descendants=[],queue=[key];while(queue.length){const current=queue.shift();entries.filter(entry=>entry.key===current||entry.parent===current).forEach(entry=>{if(!descendants.includes(entry)){descendants.push(entry);if(entry.key!==current)queue.push(entry.key)}})}return descendants}
function renderFolderOptions(source){const state=folderState[source],box=$(`#${source}-folder-options`),selected=state.entries.length-state.excluded.size,summary=$(`#${source}-folder-summary`);if(!box||!summary)return;summary.textContent=!state.entries.length?'No folders found':!state.excluded.size?`All ${state.entries.length} selected`:`${selected} of ${state.entries.length} selected`;box.innerHTML=state.entries.map(entry=>`<label class="folder-option" style="--folder-depth:${entry.depth}"><input type="checkbox" data-source="${source}" data-folder-key="${escapeHtml(entry.key)}" ${state.excluded.has(entry.key)?'':'checked'}><span>${escapeHtml(entry.label)}</span><small>${entry.count}</small></label>`).join('');box.querySelectorAll('input').forEach(input=>input.onchange=()=>{const targets=folderDescendants(source,input.dataset.folderKey);targets.forEach(entry=>input.checked?state.excluded.delete(entry.key):state.excluded.add(entry.key));persistFolders(source);renderFolderOptions(source)})}
function configureFolders(source,entries){const state=folderState[source];state.entries=entries;const saved=persistedExcluded(source);state.excluded=new Set(entries.map(entry=>entry.key).filter(key=>saved.has(key)));renderFolderOptions(source)}
fetch('/api/collections').then(r=>r.json()).then(data=>{const entries=(data.collections||[]).map(folder=>({key:String(folder.collection_id),parent:folder.parent_id==null?'':String(folder.parent_id),label:folder.name,depth:Number(folder.depth)||0,count:folder.item_count}));entries.push({key:'__unfiled__',parent:'',label:'Unfiled items',depth:0,count:data.unfiled_count||0});configureFolders('zotero',entries)}).catch(()=>{});
fetch('/api/obsidian/folders').then(r=>r.json()).then(data=>configureFolders('obsidian',(data.folders||[]).map(folder=>({key:String(folder.path),parent:'',label:folder.name,depth:Number(folder.depth)||0,count:folder.note_count})))).catch(()=>{});
['zotero','obsidian'].forEach(source=>{$(`#${source}-folder-summary`).onclick=()=>{const menu=$(`#${source}-folder-menu`),opening=menu.classList.contains('hidden');$$('.folder-menu').forEach(item=>item.classList.add('hidden'));menu.classList.toggle('hidden',!opening)}});
function closeFolderMenus(){$$('.folder-menu').forEach(item=>item.classList.add('hidden'))}
$$('[data-folder-action]').forEach(button=>button.onclick=()=>{const source=button.dataset.source,state=folderState[source];state.excluded=button.dataset.folderAction==='all'?new Set():new Set(state.entries.map(entry=>entry.key));persistFolders(source);renderFolderOptions(source)});
$('#advanced-toggle').onclick=()=>{const panel=$('#advanced-panel'),open=panel.classList.toggle('hidden')===false;$('#advanced-toggle').setAttribute('aria-expanded',String(open))};
filterIds.forEach(id=>$('#'+id).addEventListener('change',updateFilterBadge));
$('#clear-filters').onclick=()=>setFilters({});
fetch('/api/stats').then(r=>r.json()).then(s=>{$('#stats').innerHTML=`<div class="stat"><b>${s.items.toLocaleString()}</b><span>Zotero works</span></div><div class="stat"><b>${(s.obsidian?.notes||0).toLocaleString()}</b><span>Obsidian notes</span></div><div class="stat"><b>${s.annotations.toLocaleString()}</b><span>Annotations</span></div>`});
function renderLlmStatus(){
  const el=$('#llm-status'),choice=llmState?.embedding_models?.find(item=>item.model===embeddingModel),answerChoice=llmState?.answer_models?.find(item=>item.model===answerModel),semanticNeeded=retrievalMethod!=='bm25',gemmaNeeded=generateAnswerEnabled(),index=choice?.semantic_index,progress=index?.progress||{},setup=index?.setup||{},embeddingReady=!semanticNeeded||(llmState?.embedding_available&&choice?.installed&&index?.ready),gemmaReady=!gemmaNeeded||(llmState?.answer_available&&!!answerChoice),ready=embeddingReady&&gemmaReady;
  const indexed=Number(progress.indexed??index?.chunks??0),total=Number(progress.total_chunks||0),progressText=total?`${indexed.toLocaleString()} of ${total.toLocaleString()}`:`${indexed.toLocaleString()} chunks`,downloadPercent=setup.expected_bytes?Math.min(100,Math.round(100*Number(setup.download_bytes||0)/Number(setup.expected_bytes))):0,setupText=setup.state==='downloading'?`downloading · ${downloadPercent}%`:setup.state==='verifying'?'verifying download':setup.state==='registering'?'registering in Ollama':'not installed yet';
  const install=llmState?.model_install||{},installing=install.running&&install.model===embeddingModel,installPercent=install.total?Math.round(100*install.completed/install.total):0;
  let message='',detail='',canInstall=false;
  if(!llmState){message='Could not check local AI';detail='Marginalia could not read the local AI status. BM25 keyword search is still available.'}
  else if(!semanticNeeded&&!gemmaNeeded){message='BM25 ready · local AI optional';detail='Keyword search does not require Ollama.'}
  else if(!llmState.installed&&!llmState.answer_available&&!llmState.embedding_available){message='Ollama is not installed';detail='Install Ollama to use semantic search or generated answers. BM25 keyword search works without it.';canInstall=true}
  else if(semanticNeeded&&!llmState.embedding_available){message='Embedding service is not running';detail='Marginalia is starting the dedicated embedding service. BM25 remains available meanwhile.'}
  else if(installing){message=`Downloading ${embeddingLabel(embeddingModel)}${installPercent?' · '+installPercent+'%':''}`;detail=install.status||'Downloading the model locally with Ollama.'}
  else if(install.model===embeddingModel&&install.status==='failed'){message=`Could not install ${embeddingLabel(embeddingModel)}`;detail=install.error||'The Ollama model download failed.';canInstall=!!llmState.installed}
  else if(semanticNeeded&&choice&&!choice.installed){message=`${embeddingLabel(embeddingModel)} model is not downloaded`;detail='Install it here to enable semantic and hybrid search. BM25 remains available.';canInstall=!!llmState.installed}
  else if(gemmaNeeded&&!llmState.answer_available){message='Answer-model Ollama is not running';detail='Start the main Ollama service to generate answers. Search itself remains available.'}
  else if(gemmaNeeded&&!answerChoice){message=`${answerModel} answer model is not downloaded`;detail=`Download it with: ollama pull ${answerModel}, or turn off Generate model answer.`}
  else if(semanticNeeded&&!index?.ready&&progress.status==='running'){message=`${embeddingLabel(embeddingModel)} indexing · ${progressText}`;detail='Semantic search will become available when local indexing finishes.'}
  else if(semanticNeeded&&!index?.ready){message=`${embeddingLabel(embeddingModel)} index is not ready`;detail='Build this model’s index, or use BM25 keyword search now.'}
  else{message=`Local · ${embeddingLabel(embeddingModel)}${gemmaNeeded?' · '+answerModel:''}`;detail='The selected local AI features are ready.'}
  el.classList.toggle('ready',ready);el.classList.toggle('failed',!ready);
  el.querySelector('b').textContent=message;el.title=detail;const installButton=$('#install-embedding');installButton.classList.toggle('hidden',!canInstall&&!installing);installButton.disabled=installing;installButton.textContent=installing?(installPercent?`${installPercent}%`:'Downloading…'):(llmState&&!llmState.installed?'Get Ollama':'Install model')
}
function configureAnswerModels(){const select=$('#answer-model'),models=llmState?.answer_models||[],available=new Set(models.map(item=>item.model));if(models.length&&!available.has(answerModel))answerModel=available.has(llmState.model)?llmState.model:models[0].model;select.innerHTML=models.map(item=>`<option value="${escapeHtml(item.model)}">${escapeHtml(item.model)}</option>`).join('')+`<option value="__add_model__">＋ Add another model…</option>`;select.value=available.has(answerModel)?answerModel:'__add_model__';if(available.has(answerModel))localStorage.setItem('marginalia-answer-model',answerModel)}
function configureEmbeddingModels(){const select=$('#embedding-model'),models=llmState?.embedding_models||[],available=new Set(models.map(item=>item.model));if(!available.has(embeddingModel))embeddingModel=available.has(llmState?.embedding_model)?llmState.embedding_model:'qwen3-embedding:0.6b';select.innerHTML=models.map(item=>`<option value="${escapeHtml(item.model)}" ${item.semantic_index?.ready?'':'disabled'}>${escapeHtml(embeddingLabel(item.model))}${item.semantic_index?.ready?'':' · index unavailable'}</option>`).join('')+`<option value="__add_model__">＋ Add another model…</option>`;select.value=embeddingModel;localStorage.setItem('marginalia-embedding-model',embeddingModel)}
async function refreshLlmState(){try{llmState=await fetch('/api/llm-status').then(r=>r.json());configureEmbeddingModels();configureAnswerModels()}catch{llmState=null}renderLlmStatus()}
refreshLlmState();setInterval(refreshLlmState,15000);
$('#install-embedding').onclick=async()=>{if(llmState&&!llmState.installed){window.open('https://ollama.com/download/windows','_blank','noopener');return}const button=$('#install-embedding');button.disabled=true;try{await productRequest('/api/ai/install-embedding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:embeddingModel})});const poll=async()=>{await refreshLlmState();if(llmState?.model_install?.running)setTimeout(poll,1000)};poll()}catch(error){alert(error.message)}finally{button.disabled=false}};
$$('.nav').forEach(b=>b.onclick=()=>{closeFolderMenus();$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');scope=b.dataset.scope;$('#scope-label').textContent=labels[scope];if($('#query').value.trim())run()});
function generateAnswerEnabled(){return $('#generate-answer').checked}
function answerMode(){return $('#answer-mode').value==='full'?'full':'fast'}
function syncAnswerMode(){const enabled=generateAnswerEnabled();for(const id of ['answer-mode','answer-model']){const select=$('#'+id);select.disabled=!enabled;select.closest('label').classList.toggle('inactive',!enabled)}}
function effectiveExact(){return retrievalMethod==='bm25'&&$('#exact-match').checked}
function syncRetrievalControls(){
  $$('[data-retrieval]').forEach(button=>button.classList.toggle('active',button.dataset.retrieval===retrievalMethod));
  const exact=$('#exact-match'),option=$('#exact-option'),available=retrievalMethod==='bm25';exact.disabled=!available;option.classList.toggle('disabled',!available);option.title=available?'Match this exact phrase':'Exact phrase is a BM25 option. Hybrid already gives short exact phrases extra weight.'
  $('.embedding-option').classList.toggle('inactive',retrievalMethod==='bm25');renderLlmStatus();
}
function showSearchNotice(message=''){const notice=$('#search-notice');notice.textContent=message;notice.classList.toggle('hidden',!message)}
function fallBackToBm25IfNeeded(){
  if(retrievalMethod==='bm25'||!llmState)return false;
  const choice=llmState.embedding_models?.find(item=>item.model===embeddingModel),index=choice?.semantic_index;
  if(llmState.embedding_available&&choice?.installed&&index?.ready)return false;
  const previous=retrievalMethod;retrievalMethod='bm25';localStorage.setItem('marginalia-retrieval-method',retrievalMethod);syncRetrievalControls();
  showSearchNotice(`${retrievalLabels[previous]} is unavailable because ${embeddingLabel(embeddingModel)} is not ready. Switched to BM25 automatically; the answer model can still generate an answer from BM25 results.`);
  return true
}
const storedAnswer=localStorage.getItem('marginalia-generate-answer');
$('#generate-answer').checked=storedAnswer===null?true:storedAnswer==='true';
$('#answer-mode').value=localStorage.getItem('marginalia-answer-mode')==='full'?'full':'fast';
$('#answer-model').value=answerModel;
$('#embedding-model').value=embeddingModel;
$('#embedding-model').onchange=async e=>{if(e.target.value==='__add_model__'){e.target.value=embeddingModel;openAiModels();return}const previous=embeddingModel;embeddingModel=e.target.value;try{await productRequest('/api/ai/select-embedding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:embeddingModel})});localStorage.setItem('marginalia-embedding-model',embeddingModel);renderLlmStatus()}catch(error){embeddingModel=previous;e.target.value=previous;alert(error.message)}};
$('#generate-answer').onchange=()=>{localStorage.setItem('marginalia-generate-answer',String(generateAnswerEnabled()));syncAnswerMode();renderLlmStatus()};
$('#answer-mode').onchange=()=>localStorage.setItem('marginalia-answer-mode',answerMode());
$('#answer-model').onchange=e=>{if(e.target.value==='__add_model__'){e.target.value=answerModel;openAiModels();return}answerModel=e.target.value;localStorage.setItem('marginalia-answer-model',answerModel);renderLlmStatus()};
syncAnswerMode();
$$('[data-retrieval]').forEach(button=>button.onclick=()=>{retrievalMethod=button.dataset.retrieval;localStorage.setItem('marginalia-retrieval-method',retrievalMethod);showSearchNotice();syncRetrievalControls()});
syncRetrievalControls();
$$('.prompts button').forEach(b=>b.onclick=()=>{$('#query').value=b.textContent;run()});
$('#search-form').onsubmit=e=>{e.preventDefault();run()};
$('#query').oninput=e=>{e.target.style.height='auto';e.target.style.height=e.target.scrollHeight+'px'};
$('#query').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#search-form').requestSubmit()}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#query').focus()}if(e.key==='Escape'&&$('#item-dialog').open)$('#item-dialog').close()});
$('#item-dialog .close').onclick=()=>$('#item-dialog').close();
$('#context-dialog .close').onclick=()=>$('#context-dialog').close();
$('#maximize-context').onclick=()=>{const dialog=$('#context-dialog'),button=$('#maximize-context'),max=dialog.classList.toggle('maximized');button.textContent=max?'▣':'□';button.title=max?'Restore reader':'Maximize reader';button.setAttribute('aria-label',button.title)};
$('#context-dialog').addEventListener('close',()=>{$('#context-dialog').classList.remove('maximized');$('#maximize-context').textContent='□';if(contextRequest)contextRequest.abort();contextRequest=null;contextSequence++;readerState=null});
function beginProgress(){if(activeRequest)activeRequest.abort();activeRequest=new AbortController();progressPhase='retrieval';clearInterval(progressTimer);clearInterval(answerProgressTimer);progressStartedAt=performance.now();progressValue=4;answerProgressValue=0;const box=$('#search-progress'),bar=$('#progress-bar'),label=$('#progress-label'),clock=$('#progress-time'),answerBox=$('#answer-progress'),answerBar=$('#answer-progress-bar');box.classList.remove('hidden');answerBox.classList.add('hidden');bar.className='progress-bar';bar.style.width=progressValue+'%';answerBar.className='progress-bar answer-progress-bar';answerBar.style.width='4%';clock.textContent='0.0s';$('#answer-progress-time').textContent='0.0s';const corpus={all:'Zotero and Obsidian',annotations:'all of your annotations',documents:'full PDF text',metadata:'Zotero titles and metadata',notes:'Zotero Notes',obsidian:'Obsidian Notes'}[scope],model=retrievalMethod==='bm25'?'':` using ${embeddingLabels[embeddingModel]}`;label.textContent=`Searching ${corpus} with ${retrievalLabels[retrievalMethod]}${model}...`;progressTimer=setInterval(()=>{const seconds=(performance.now()-progressStartedAt)/1000,target=Math.min(92,6+84*(1-Math.exp(-seconds/6)));progressValue=Math.max(progressValue,target);clock.textContent=seconds.toFixed(1)+'s';bar.style.width=progressValue+'%';if(seconds>20&&retrievalMethod!=='bm25'&&embeddingModel==='qwen3-embedding:8b')label.textContent='Qwen3 8B is embedding the query and ranking the library...';else if(seconds>20)label.textContent='Library retrieval is still in progress...';else if(seconds>8)label.textContent='Ranking the strongest matches...'},150);return activeRequest.signal}
function finishRetrievalProgress(ok=true){clearInterval(progressTimer);const elapsed=progressStartedAt?(performance.now()-progressStartedAt)/1000:0,bar=$('#progress-bar');resultState.retrievalSeconds=elapsed;progressValue=100;bar.style.width='100%';bar.classList.add(ok?'done':'failed');$('#progress-time').textContent=elapsed.toFixed(1)+'s';$('#progress-label').textContent=ok?'Results ready':'Search failed - please try again';if(!ok)progressPhase='idle'}
function endProgress(ok=true){finishRetrievalProgress(ok);progressPhase='idle'}
function citationButton(number,occurrence){const index=Number(number)-1,source=answerSources[index],evidence=answerEvidence.find(item=>item.occurrence===occurrence&&item.source_index===index);return source?`<button class="answer-citation ${evidence?'evidence-ready':''}" data-citation-index="${index}" data-citation-occurrence="${occurrence}" title="${evidence?'Open exact supporting passage':'Open source'} ${number}: ${escapeHtml(source.title||source.label||'Library passage')}">[${number}]</button>`:`<span class="answer-citation missing">[${number}]</span>`}
function answerMarkup(value){let occurrence=0;const inline=value=>escapeHtml(value).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\[((?:\d+\s*,\s*)*\d+)\]/g,(_,numbers)=>numbers.split(',').map(number=>citationButton(number.trim(),occurrence++)).join(' ')),lines=String(value||'').split(/\r?\n/),html=[],list=[];const flush=()=>{if(list.length){html.push('<ul>'+list.splice(0).map(item=>`<li>${inline(item)}</li>`).join('')+'</ul>')}};lines.forEach(line=>{const bullet=line.match(/^\s*[*-]\s+(.+)/);if(bullet){list.push(bullet[1]);return}flush();if(line.trim())html.push(`<p>${inline(line.trim())}</p>`)});flush();return html.join('')}
function appendStreamCursor(html){const cursor='<i class="stream-cursor answer-token-cursor" aria-hidden="true"></i>';if(/<\/li><\/ul>$/.test(html))return html.replace(/<\/li><\/ul>$/,cursor+'</li></ul>');if(/<\/p>$/.test(html))return html.replace(/<\/p>$/,cursor+'</p>');return html+cursor}
function beginAnswerProgress(model){finishRetrievalProgress(true);progressPhase='answer';clearInterval(answerProgressTimer);answerProgressStartedAt=performance.now();answerProgressValue=4;const box=$('#answer-progress'),bar=$('#answer-progress-bar'),label=$('#answer-progress-label'),clock=$('#answer-progress-time'),name=model||answerModel||'The answer model';box.classList.remove('hidden');bar.className='progress-bar answer-progress-bar';bar.style.width='4%';clock.textContent='0.0s';label.textContent=`Local ${name} is waiting for Ollama and preparing the passages...`;answerProgressTimer=setInterval(()=>{const seconds=(performance.now()-answerProgressStartedAt)/1000,target=Math.min(94,6+86*(1-Math.exp(-seconds/18)));answerProgressValue=Math.max(answerProgressValue,target);clock.textContent=seconds.toFixed(1)+'s';bar.style.width=answerProgressValue+'%';if(seconds>20&&progressPhase==='answer')label.textContent=`${name} is preparing the context and processing the prompt...`},150)}
function finishAnswerProgress(ok=true,metrics=null){progressPhase='idle';clearInterval(answerProgressTimer);const elapsed=answerProgressStartedAt?(performance.now()-answerProgressStartedAt)/1000:0,bar=$('#answer-progress-bar');resultState.answerSeconds=elapsed;answerProgressValue=100;bar.style.width='100%';bar.classList.add(ok?'done':'failed');$('#answer-progress-time').textContent=elapsed.toFixed(1)+'s';if(ok&&metrics){const seconds=value=>(Number(value||0)/1e9).toFixed(1),evidence=resultState.evidenceStatus==='failed'?' · evidence localization unavailable':` · ${answerEvidence.length} evidence passages located`;$('#answer-progress-label').textContent=`Answer complete · load ${seconds(metrics.load_duration)}s · prompt ${seconds(metrics.prompt_eval_duration)}s · writing ${seconds(metrics.eval_duration)}s${evidence}`}else $('#answer-progress-label').textContent=ok?'Answer complete':'Answer generation stopped'}
async function streamGemmaAnswer(data,methodLabel,q,signal){
  const box=$('#answer'),generator=data.model||answerModel||'Local model';let answerText='',done=false,writingDone=false,answerMetrics=null,paintQueued=false,paintTimer=null,lastPaint=0,streamArea,status;
  answerSources=[];answerEvidence=[];resultState.evidenceStatus='pending';box.classList.remove('hidden');
  box.innerHTML=`<div class="answer-heading"><h2>Answer from your library</h2><span>Local · ${escapeHtml(generator)} · ${escapeHtml(methodLabel)} · ${data.answer_mode==='full'?'Full answer':'Fast answer'}</span></div><div class="answer-text" id="streamed-answer"></div><div class="answer-stream-status" id="answer-stream-status"><span class="load-spinner"></span><span>${escapeHtml(generator)} is starting…</span></div>`;
  streamArea=$('#streamed-answer');status=$('#answer-stream-status');
  const paint=()=>{paintQueued=false;lastPaint=performance.now();if(!streamArea)return;const markup=answerMarkup(answerText);streamArea.innerHTML=!writingDone&&answerText?appendStreamCursor(markup):markup;bindAnswerCitations(streamArea)};
  const schedulePaint=()=>{if(paintQueued)return;paintQueued=true;const delay=Math.max(0,90-(performance.now()-lastPaint));paintTimer=setTimeout(()=>requestAnimationFrame(paint),delay)};
  const handleEvent=event=>{if(event.type==='meta'){answerSources=event.sources||[];const contextSize=Number(event.num_ctx||0).toLocaleString(),promptEstimate=Number(event.prompt_tokens_estimate||0).toLocaleString(),detail=event.queued?'Another local answer task is finishing…':`${generator} is preparing ${answerSources.length} sources · requested context ${contextSize} tokens · estimated prompt ${promptEstimate} tokens…`;if(status)status.querySelector('span:last-of-type').textContent=detail;$('#answer-progress-label').textContent=detail}else if(event.type==='status'){const detail=event.message||`${generator} is preparing the answer…`;if(status)status.querySelector('span:last-of-type').textContent=detail;$('#answer-progress-label').textContent=detail}else if(event.type==='token'){answerText+=event.text||'';progressPhase='writing';if(status)status.querySelector('span:last-of-type').textContent=`${generator} is writing…`;$('#answer-progress-label').textContent=`${generator} is writing the answer from the retrieved passages...`;schedulePaint()}else if(event.type==='metrics')answerMetrics=event;else if(event.type==='evidence_status'){progressPhase='evidence';resultState.evidenceStatus='locating';const detail=event.message||`${generator} is locating exact evidence for the citations…`;status?.classList.add('evidence-locating');$('#answer-progress-bar').classList.add('evidence-stage');if(status)status.querySelector('span:last-of-type').textContent=detail;$('#answer-progress-label').textContent=detail}else if(event.type==='evidence'){answerEvidence=event.items||[];resultState.evidenceStatus='ready';paint();if(status)status.querySelector('span:last-of-type').textContent=`Located exact evidence for ${answerEvidence.length} of ${event.citation_count||0} citations.`}else if(event.type==='evidence_error'){resultState.evidenceStatus='failed';if(status)status.querySelector('span:last-of-type').textContent='The answer is ready, but exact evidence positions could not be resolved.'}else if(event.type==='done')done=true;else if(event.type==='error')throw new Error(event.detail||`${generator} stopped before completing the answer.`)};
  const processEvent=event=>{if(event.type==='evidence_status'){writingDone=true;paint()}handleEvent(event)};
  try{
    const response=await fetch('/api/ask/compose',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/x-ndjson'},body:JSON.stringify({retrieval_token:data.retrieval_token,stream:true}),signal});
    if(!response.ok){let detail='';try{const problem=await response.json();detail=problem.detail||problem.error||''}catch{detail=await response.text()}throw new Error(detail||`Answer request failed (${response.status})`)}
    if(!response.body||!(response.headers.get('content-type')||'').includes('application/x-ndjson'))throw new Error('The server did not provide a valid answer stream.');
    const reader=response.body.getReader(),decoder=new TextDecoder();let pending='';
    while(true){const {done:readerDone,value}=await reader.read();pending+=decoder.decode(value||new Uint8Array(),{stream:!readerDone});const lines=pending.split('\n');pending=readerDone?(lines.pop()||''):lines.pop();for(const line of lines){if(line.trim())processEvent(JSON.parse(line))}if(readerDone)break}
    if(pending.trim())processEvent(JSON.parse(pending));
    if(!done)throw new Error('The answer stream ended unexpectedly.');
    if(!answerText.trim())throw new Error(`${generator} returned an empty answer.`);
    clearTimeout(paintTimer);paint();if(status)status.remove();finishAnswerProgress(true,answerMetrics);currentAnswerText=answerText;currentAnswerMetrics=answerMetrics;await saveHistorySnapshot()
  }catch(e){
    if(e.name==='AbortError'){clearTimeout(paintTimer);return}clearTimeout(paintTimer);paint();finishAnswerProgress(false);currentAnswerText=answerText;currentAnswerMetrics=answerMetrics;saveHistorySnapshot();box.classList.remove('hidden');
    const message=e.message||`The local ${generator} connection was interrupted.`;
    if(status){status.className='answer-stream-error';status.innerHTML=`${escapeHtml(message)} <button class="retry-answer" id="retry-gemma-answer">Retry answer</button>`}
    const retry=$('#retry-gemma-answer');if(retry)retry.onclick=()=>{beginAnswerProgress(data.model);streamGemmaAnswer(data,methodLabel,q,signal)}
  }
}
function run(){const q=$('#query').value.trim();if(!q||!validFilters())return;historySourceCurrent=true;fallBackToBm25IfNeeded();answerSources=[];answerEvidence=[];currentAnswerText='';currentAnswerMetrics=null;currentHistoryId=null;closeFolderMenus();$('#history-notice').classList.add('hidden');$('#welcome').classList.add('hidden');$('#results').innerHTML='<div class="empty">Your search is running. Progress appears above.</div>';$('#answer').classList.add('hidden');search(q)}
async function search(q){
  const signal=beginProgress(),requestedMethod=retrievalMethod,model=embeddingModel,exact=effectiveExact(),generateAnswer=generateAnswerEnabled(),filters=currentFilters();
  expandedGroups.clear();publicationMatches.clear();resultState={query:q,scope,method:requestedMethod,embeddingModel:model,exact,generateAnswer,filters,results:[],hasMore:false,loading:true};
  let resultsReady=false;
  try{
    const extra=filterParams(filters),url=`/api/search?q=${encodeURIComponent(q)}&scope=${scope}&method=${requestedMethod}&embedding_model=${encodeURIComponent(model)}&exact=${exact?1:0}&generate_answer=${generateAnswer?1:0}&answer_mode=${answerMode()}&answer_model=${encodeURIComponent(answerModel)}&offset=0${extra?'&'+extra:''}`;
    const response=await fetch(url,{signal}),data=await response.json();if(!response.ok)throw new Error(data.detail||data.error||'Search failed');
    const method=data.method||requestedMethod,warnings=[];if(data.fallback_reason){retrievalMethod='bm25';localStorage.setItem('marginalia-retrieval-method','bm25');syncRetrievalControls();warnings.push(`${data.fallback_reason} Switched to BM25 automatically.`)}
    if(data.answer_warning){$('#generate-answer').checked=false;localStorage.setItem('marginalia-generate-answer','false');syncAnswerMode();renderLlmStatus();warnings.push(data.answer_warning)}if(warnings.length)showSearchNotice(warnings.join(' '));
    const effectiveGenerate=!!data.generate_answer;
    resultState={query:q,scope,method,embeddingModel:model,exact:data.exact??exact,generateAnswer:effectiveGenerate,answerModel:data.model||answerModel,answerMode:answerMode(),filters,results:data.results||[],hasMore:!!data.has_more,loading:false};resultsReady=true;render(resultState.results,q);finishRetrievalProgress(true);await saveHistorySnapshot();
    if(!effectiveGenerate||!data.retrieval_token){progressPhase='idle';return}
    const modelLabel=method==='bm25'?'':` · ${embeddingLabels[data.embedding_model]||data.embedding_model}`,methodLabel=(data.retrieval_method||retrievalLabels[method])+modelLabel;
    beginAnswerProgress(data.model);await streamGemmaAnswer(data,methodLabel,q,signal);

  }catch(e){
    if(e.name==='AbortError')return;resultState.loading=false;const box=$('#answer');
    if(resultsReady){finishRetrievalProgress(true);finishAnswerProgress(false);const interrupted=e instanceof TypeError||/network|fetch|connection|refused/i.test(e.message||''),message=interrupted?'The local model connection was interrupted. Ollama can be retried without losing this search.':e.message||'Make sure Ollama is running.';box.classList.remove('hidden');box.innerHTML=`<h2>The results are ready, but the selected model could not compose an answer</h2><div>${escapeHtml(message)}</div><button class="retry-answer" id="retry-gemma-answer">Retry answer</button>`;$('#retry-gemma-answer').onclick=()=>search(q)}
    else{endProgress(false);$('#results').innerHTML=`<div class="empty">The search could not be completed. ${escapeHtml(e.message||'Please try again.')}</div>`}
  }
}
function authorLinks(authors,clickable=true){return (authors||[]).map(a=>clickable?`<button class="author-link" data-author="${escapeHtml(a.name)}">${escapeHtml(a.name)}</button>`:`<span class="note-author">${escapeHtml(a.name)}</span>`).join('<span class="author-sep">, </span>')}
function dateLabel(value,added=false){if(!value)return'';if(!added)return escapeHtml(String(value));const d=new Date(String(value).replace(' ','T')+'Z');return isNaN(d)?escapeHtml(value):d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function sourceIdentity(source){if(source.semantic_chunk_id!=null)return JSON.stringify(['semantic-chunk',source.semantic_chunk_id]);return JSON.stringify([source.kind,source.item_id,source.attachment_id,source.page,source.annotation_id,source.embedded_annotation_id,source.note_id,source.obsidian_note_id,source.obsidian_section_id,source.section_title].map(value=>value??null))}
function sourceGroupKey(source){return source.item_id?`zotero:${source.item_id}`:source.obsidian_note_id?`obsidian:${source.obsidian_note_id}`:null}
function citationRow(source,index,evidence=null,chunk=''){const matchId=`citation-${index}-${Date.now()}`,match={...source},evidenceText=evidence&&chunk?chunk.slice(evidence.start,evidence.end):'';if(evidenceText)match._evidence_text=evidenceText;matchRegistry.set(matchId,match);return{dataset:{matchId,item:String(source.item_id||''),attachment:String(source.attachment_id||''),page:String(source.page||''),kind:String(source.kind||''),annotation:String(source.annotation_id||''),embedded:String(source.embedded_annotation_id||''),note:String(source.note_id||''),obsidianNote:String(source.obsidian_note_id||''),obsidianSection:String(source.obsidian_section_id||''),evidenceText}}}
function bindAnswerCitations(root=document){[...root.querySelectorAll('.answer-citation[data-citation-index]')].forEach(button=>button.onclick=()=>showAnswerCitation(Number(button.dataset.citationIndex),Number(button.dataset.citationOccurrence)))}
function focusResultSource(source){const identity=sourceIdentity(source),match=resultState.results.find(result=>sourceIdentity(result)===identity);if(!match)return;if(source.citation_text)match.citation_text=source.citation_text;const groupKey=sourceGroupKey(match);if(groupKey){expandedGroups.add(groupKey);if(publicationMatches.has(groupKey)){const matches=publicationMatches.get(groupKey),listed=matches.find(result=>sourceIdentity(result)===identity);if(listed&&source.citation_text)listed.citation_text=source.citation_text;else if(!listed)publicationMatches.set(groupKey,[match,...matches])}}const dialog=$('#context-dialog');if(dialog.open)dialog.close();render(resultState.results,resultState.query);requestAnimationFrame(()=>{const target=$$('.match-row').find(row=>row.dataset.sourceKey===identity);if(!target)return;target.classList.add('citation-target');target.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>target.classList.remove('citation-target'),2800)})}
function evidenceMarkup(text,evidence){if(!evidence||evidence.start<0||evidence.end<=evidence.start||evidence.end>text.length)return highlightContext(text,resultState.query,resultState.exact);return escapeHtml(text.slice(0,evidence.start))+`<mark class="citation-evidence">${escapeHtml(text.slice(evidence.start,evidence.end))}</mark>`+escapeHtml(text.slice(evidence.end))}
function showAnswerCitation(index,occurrence=-1){const source=answerSources[index];if(!source)return;const evidence=answerEvidence.find(item=>item.occurrence===occurrence&&item.source_index===index),dialog=$('#context-dialog'),detail=$('#context-detail'),isObsidian=source.kind==='obsidian',authors=authorLinks(source.authors||[],!isObsidian),chunk=source.citation_text||snippetAnchor(source.snippet||'')||'No passage text is available.',evidenceText=evidence?chunk.slice(evidence.start,evidence.end):'',sourceKey=sourceIdentity(source),canRead=!!(source.attachment_id||source.annotation_id||source.embedded_annotation_id||source.note_id||source.obsidian_note_id),section=source.section_title?` · ${escapeHtml(source.section_title)}`:'',page=source.page?` · page ${escapeHtml(source.page)}`:'';if(contextRequest)contextRequest.abort();contextRequest=null;contextSequence++;readerState=null;detail.innerHTML=`<div class="context-shell"><header class="context-header"><div class="result-meta">Answer source [${index+1}] · ${escapeHtml(source.label||source.kind||'Library passage')}${section}${page}</div><h2>${escapeHtml(source.title||'Library source')}</h2><div class="bibliographic-line">${authors}${source.published?`<span>Published ${dateLabel(source.published)}</span>`:''}${source.date_added?`<span>Added ${dateLabel(source.date_added,true)}</span>`:''}${source.created?`<span>Created ${dateLabel(source.created,true)}</span>`:''}${source.modified?`<span>Edited ${dateLabel(source.modified,true)}</span>`:''}${source.vault_path?`<span class="vault-path">${escapeHtml(source.vault_path)}</span>`:''}</div><div class="context-actions">${source.attachment_id?`<a href="/api/file/${source.attachment_id}" target="_blank">Open original PDF ↗</a>`:''}${canRead?'<button id="citation-full-context">Read in full context</button>':''}<button id="citation-show-result">Show this match in results ↓</button></div></header><div class="context-page" tabindex="0"><section class="citation-source"><div class="citation-source-heading">${evidence?'Exact evidence selected by the answer model':'Passage used by the answer model'}</div><div class="citation-passage">${evidenceMarkup(chunk,evidence)}</div></section></div></div>`;if(!dialog.open)dialog.showModal();const scroller=$('#context-dialog .context-page');if(scroller)scroller.focus({preventScroll:true});requestAnimationFrame(()=>detail.querySelector('.citation-evidence')?.scrollIntoView({block:'center'}));$$(`#context-dialog .author-link`).forEach(link=>link.onclick=e=>{e.preventDefault();dialog.close();showAuthor(link.dataset.author)});$('#citation-show-result').onclick=()=>focusResultSource(source);const read=$('#citation-full-context');if(read)read.onclick=()=>{const selectedEvidence=detail.querySelector('.citation-evidence')?.textContent||evidenceText,row=citationRow(source,index,evidence,chunk);showContext(row,sourceKey,selectedEvidence)}}
function grouped(results){const map=new Map();results.forEach((r,i)=>{const key=r.item_id?`zotero:${r.item_id}`:r.obsidian_note_id?`obsidian:${r.obsidian_note_id}`:`loose-${r.kind}-${i}`;if(!map.has(key))map.set(key,{key,item:r,matches:[]});map.get(key).matches.push(r)});return [...map.values()].map(g=>({...g,matches:publicationMatches.get(g.key)||g.matches}))}
function matchMarkup(r){const matchId='match-'+(++matchSequence);matchRegistry.set(matchId,r);const section=r.section_title?` · ${escapeHtml(r.section_title)}`:'',plainBm25=resultState.method==='bm25',citation=r.citation_text?`<p class="citation-result-text">${plainBm25?escapeHtml(r.citation_text):highlightContext(r.citation_text,resultState.query,resultState.exact)}</p>`:'',snippet=r.snippet?(plainBm25?String(r.snippet).replace(/<\/?mark\b[^>]*>/gi,''):r.snippet):'';return `<div class="match-row ${r.kind==='obsidian'?'obsidian-match':''}" data-match-id="${matchId}" data-source-key="${escapeHtml(sourceIdentity(r))}" data-item="${r.item_id||''}" data-attachment="${r.attachment_id||''}" data-page="${escapeHtml(r.page||'')}" data-kind="${escapeHtml(r.kind)}" data-annotation="${r.annotation_id||''}" data-embedded="${r.embedded_annotation_id||''}" data-note="${r.note_id||''}" data-obsidian-note="${r.obsidian_note_id||''}" data-obsidian-section="${r.obsidian_section_id||''}"><div class="match-label">${escapeHtml(r.label)}${section}${r.generated_from_annotations?'<span class="annotation-derived">Generated from annotations</span>':''}${r.page?' · page '+escapeHtml(r.page):''}</div>${citation||(snippet?`<p>${snippet}</p>`:'<p class="metadata-match">Bibliographic record match</p>')}<button class="match-open" data-pdf="${r.attachment_id||''}">${r.attachment_id?'Open PDF ↗':r.kind==='obsidian'?'Read note →':'Details →'}</button></div>`}
function render(results,q,heading='Results'){const el=$('#results');matchRegistry.clear();matchSequence=0;if(!results.length){el.innerHTML='<div class="empty">No matches found. Try fewer or broader words.</div>';return}const groups=grouped(results);el.innerHTML=`<div class="results-head"><h2>${escapeHtml(heading)}</h2><span>${results.length} matches in ${groups.length} sources</span></div>`+groups.map(g=>{const r=g.item,isObsidian=!!r.obsidian_note_id,open=expandedGroups.has(g.key),hasOverflow=g.matches.length>3,visible=open?g.matches:g.matches.slice(0,3),source=isObsidian?'Obsidian note':'Publication';return `<article class="publication-group ${isObsidian?'obsidian-group':''}"><div class="publication-head"><div class="result-icon">${isObsidian?'◇':'◫'}</div><div><div class="result-meta">${source} · ${g.matches.length} ${g.matches.length===1?'match':'matches'}</div><h3 class="publication-title" data-item="${r.item_id||''}" data-obsidian-note="${r.obsidian_note_id||''}">${escapeHtml(r.title)}</h3><div class="bibliographic-line">${authorLinks(r.authors,!isObsidian)}${isObsidian&&r.vault_path?`<span class="vault-path">${escapeHtml(r.vault_path)}</span>`:''}${r.published?`<span>Published ${dateLabel(r.published)}</span>`:''}${r.date_added?`<span>Added ${dateLabel(r.date_added,true)}</span>`:''}${r.created?`<span>Created ${dateLabel(r.created,true)}</span>`:''}${r.modified?`<span>Edited ${dateLabel(r.modified,true)}</span>`:''}</div></div></div><div class="group-matches ${open?'expanded':''}">${visible.map(matchMarkup).join('')}</div>${hasOverflow?`<div class="group-toggle-row"><button class="group-toggle" data-group="${g.key}" data-item="${r.item_id||''}" data-obsidian-note="${r.obsidian_note_id||''}">${open?'Collapse':'Show all '+g.matches.length+' matches'} <span>${open?'−':'+'}</span></button></div>`:''}</article>`}).join('')+(heading==='Results'?(resultState.hasMore?'<div class="load-more" id="load-more"><span class="load-spinner"></span>Scroll for more sources and matches</div>':'<div class="all-loaded">All matching results loaded</div>'):'');bindResults()}
function staleHistoryNotice(){alert('This saved result belongs to an older library generation. Its saved text is still available, but current files and context are disabled to prevent opening the wrong source. Use Search again to reconnect it to the current library.')}
function bindResults(){$$('.match-row').forEach(row=>row.onclick=()=>{if(!historySourceCurrent)return staleHistoryNotice();if(row.dataset.kind==='metadata'&&!row.dataset.attachment)showItem(row.dataset.item);else showContext(row)});$$('.match-open').forEach(button=>button.onclick=e=>{e.stopPropagation();if(!historySourceCurrent)return staleHistoryNotice();const row=button.closest('.match-row');if(button.dataset.pdf)window.open('/api/file/'+button.dataset.pdf,'_blank');else if(row.dataset.kind==='obsidian')showContext(row);else showItem(row.dataset.item)});$$('.publication-title').forEach(title=>title.onclick=()=>{if(!historySourceCurrent)return staleHistoryNotice();if(title.dataset.obsidianNote)title.closest('.publication-group').querySelector('.match-row')?.click();else showItem(title.dataset.item)});$$('.group-toggle').forEach(button=>button.onclick=()=>toggleGroup(button.dataset.group,button.dataset.item,button.dataset.obsidianNote,button));$$('.author-link').forEach(link=>link.onclick=e=>{e.stopPropagation();showAuthor(link.dataset.author)})}
function highlightContext(text,query,exact){let safe=escapeHtml(text||'');const words=exact?[query]:String(query||'').match(/[\p{L}\p{N}]+/gu)||[];words.filter(x=>x.length>1).sort((a,b)=>b.length-a.length).slice(0,20).forEach(word=>{const escaped=word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');safe=safe.replace(new RegExp(`(${escaped})`,'giu'),'<mark>$1</mark>')});return safe}
function obsidianAssetUrl(path,notePath=''){return'/api/obsidian/asset?'+new URLSearchParams({path:String(path||'').trim(),note_path:notePath})}
function markdownInline(value,notePath=''){
  const asset=(path,label,image)=>image?`<img class="obsidian-image" data-obsidian-asset src="${obsidianAssetUrl(path,notePath)}" alt="${escapeHtml(label||path)}">`:`<a class="obsidian-embed" href="${obsidianAssetUrl(path,notePath)}" target="_blank">${escapeHtml(label||path)} ↗</a>`;
  let safe=escapeHtml(value);
  safe=safe.replace(/!\[\[([^]|]+)(?:\|[^]]+)?\]\]/g,(_,path)=>asset(path,path,/\.(?:png|jpe?g|gif|webp|svg)$/i.test(path)));
  safe=safe.replace(/!\[([^]]*)\]\((?!https?:\/\/)([^)]+)\)/gi,(_,label,path)=>asset(path,label,true));
  safe=safe.replace(/\[\[([^]|#]+)(?:#[^]|]+)?(?:\|([^]]+))?\]\]/g,(_,target,label)=>`<span class="obsidian-wikilink">${escapeHtml(label||target)}</span>`);
  safe=safe.replace(/\[([^]]+)\]\((https?:\/\/[^)]+)\)/g,(_,label,url)=>`<a href="${url}" target="_blank" rel="noreferrer">${label}</a>`);
  safe=safe.replace(/\[([^]]+)\]\((?!https?:\/\/)([^)]+)\)/gi,(_,label,path)=>asset(path,label,false));
  return safe.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/__(.+?)__/g,'<strong>$1</strong>').replace(/(?<!\*)\*([^*]+)\*(?!\*)/g,'<em>$1</em>')
}
function bindObsidianAssets(root){root?.querySelectorAll('[data-obsidian-asset]').forEach(image=>image.addEventListener('error',()=>{const warning=document.createElement('span');warning.className='obsidian-asset-error';warning.textContent=`Asset unavailable or ambiguous: ${image.alt||'unnamed asset'}`;image.replaceWith(warning)},{once:true}))}
function markdownMarkup(markdown,notePath=''){const lines=String(markdown||'').replace(/\r/g,'').split('\n'),html=[];let paragraph=[],list=[],ordered=false,code=[],inCode=false;const inline=value=>markdownInline(value,notePath),flushParagraph=()=>{if(paragraph.length){html.push(`<p>${inline(paragraph.join(' '))}</p>`);paragraph=[]}};const flushList=()=>{if(list.length){html.push(`<${ordered?'ol':'ul'}>${list.map(item=>`<li>${inline(item)}</li>`).join('')}</${ordered?'ol':'ul'}>`);list=[]}};lines.forEach(line=>{if(/^```/.test(line.trim())){flushParagraph();flushList();if(inCode){html.push(`<pre><code>${escapeHtml(code.join('\n'))}</code></pre>`);code=[]}inCode=!inCode;return}if(inCode){code.push(line);return}const heading=line.match(/^(#{1,6})\s+(.+)/);if(heading){flushParagraph();flushList();const level=Math.min(4,heading[1].length+1);html.push(`<h${level}>${inline(heading[2])}</h${level}>`);return}const bullet=line.match(/^\s*[-*+]\s+(?:\[[ xX]\]\s*)?(.+)/),number=line.match(/^\s*\d+[.)]\s+(.+)/);if(bullet||number){flushParagraph();const nextOrdered=!!number;if(list.length&&ordered!==nextOrdered)flushList();ordered=nextOrdered;list.push((bullet||number)[1]);return}if(/^\s*>/.test(line)){flushParagraph();flushList();html.push(`<blockquote>${inline(line.replace(/^\s*>\s?/,''))}</blockquote>`);return}if(/^\s*---+\s*$/.test(line)){flushParagraph();flushList();html.push('<hr>');return}if(!line.trim()){flushParagraph();flushList();return}paragraph.push(line.trim())});flushParagraph();flushList();if(code.length)html.push(`<pre><code>${escapeHtml(code.join('\n'))}</code></pre>`);return html.join('')}
async function showContext(row,linkedSourceKey='',directEvidence=''){
  if(!historySourceCurrent)return staleHistoryNotice();
  const dialog=$('#context-dialog'),detail=$('#context-detail'),kind=row.dataset.kind;
  const clickedMatch=matchRegistry.get(row.dataset.matchId)||null;
  if(contextRequest)contextRequest.abort();contextRequest=new AbortController();const request=contextRequest,sequence=++contextSequence;
  detail.innerHTML='<div class="context-loading"><span class="load-spinner"></span>&nbsp; Loading textual context...</div>';if(!dialog.open)dialog.showModal();
  const exactEvidence=directEvidence||row.dataset.evidenceText||clickedMatch?._evidence_text||'',readerEvidence=evidenceReaderAnchors(exactEvidence).join(' '),p=new URLSearchParams({attachment_id:row.dataset.attachment||'',page:row.dataset.page||'',annotation_id:row.dataset.annotation||'',embedded_annotation_id:row.dataset.embedded||'',note_id:row.dataset.note||'',obsidian_note_id:row.dataset.obsidianNote||'',obsidian_section_id:row.dataset.obsidianSection||'',match_text:readerEvidence||snippetAnchor(clickedMatch?.snippet||'')});
  try{
    const response=await fetch('/api/context?'+p,{signal:request.signal});if(!response.ok)throw new Error('Context request failed');const data=await response.json();if(sequence!==contextSequence)return;const isObsidian=kind==='obsidian',authors=authorLinks(data.authors||[],!isObsidian),isAnnotation=kind==='annotation'||kind==='embedded_annotation',isNote=kind==='note'||kind==='annotation_note';
    const focus=isAnnotation?data.annotation_text||data.comment||'':isNote?data.note_text||'':'';
    const sourceLabel=isObsidian?'Opened from: Obsidian Note':kind==='annotation'?'Opened from: My Zotero annotation':kind==='embedded_annotation'?'Opened from: Annotation embedded in PDF':isNote?'Opened from: Zotero Note':'Opened from: PDF text';
    const focusLabel=kind==='annotation'?'Your Zotero highlight':kind==='embedded_annotation'?'Highlight embedded in the PDF':'Zotero Note';
    const hasReader=!!(data.attachment_id&&data.has_document_text),fallbackText=exactEvidence||snippetAnchor(clickedMatch?.snippet||'')||data.note_text||focus||data.page_text||'No textual content is available.';
    const documentArea=isObsidian?`<article class="obsidian-note-body reader-content">${markdownMarkup(data.markdown||'',data.vault_path||'')}</article>`:hasReader?`<section class="context-section document-reader"><div class="reader-toolbar"><button id="reader-from-start">Read from page 1</button><button id="reader-back-match">Back to matched page</button><span id="reader-progress">Preparing document…</span></div><div class="reader-load reader-load-prev" id="reader-load-prev"></div><div class="document-pages" id="document-pages"></div><div class="reader-load" id="reader-load"><span class="load-spinner"></span> Loading pages…</div></section>`:`<section class="context-section"><div class="page-text clicked-match-highlight">${highlightContext(fallbackText,resultState.query,resultState.exact)}</div></section>`;
    const displayPage=data.reader_page||data.page,pathLine=isObsidian&&data.vault_path?`<span class="vault-path">${escapeHtml(data.vault_path)}</span>`:'';detail.innerHTML=`<div class="context-shell"><header class="context-header"><div class="result-meta">${sourceLabel}${displayPage?' · page '+escapeHtml(displayPage):''}</div><h2>${escapeHtml(data.title||data.note_title||clickedMatch?.title||'Library text')}</h2><div class="bibliographic-line">${authors}${pathLine}${data.created?`<span>Created ${dateLabel(data.created,true)}</span>`:''}${data.modified?`<span>Edited ${dateLabel(data.modified,true)}</span>`:''}</div><div class="context-actions">${data.attachment_id?`<a href="/api/file/${data.attachment_id}" target="_blank">Open original PDF ↗</a>`:''}${linkedSourceKey?'<button id="context-show-result">Show this match in results ↓</button>':''}<span>The clicked passage is highlighted in context</span></div></header><div class="context-page" tabindex="0">${documentArea}</div></div>`;
    const scroller=$('#context-dialog .context-page');if(scroller)scroller.focus({preventScroll:true});
    $$(`#context-dialog .author-link`).forEach(link=>link.onclick=e=>{e.preventDefault();dialog.close();showAuthor(link.dataset.author)});
    const resultLink=$('#context-show-result');if(resultLink)resultLink.onclick=()=>{const source=resultState.results.find(result=>sourceIdentity(result)===linkedSourceKey)||clickedMatch;if(source)focusResultSource(source)};
    if(hasReader){await startDocumentReader(data.attachment_id,Number(data.reader_page||1),clickedMatch,exactEvidence)}else if(isObsidian){const body=$('.obsidian-note-body');bindObsidianAssets(body);const anchors=exactEvidence?evidenceReaderAnchors(exactEvidence):snippetPassages(clickedMatch?.snippet||''),target=body?placeExactPassages(body,anchors,exactEvidence?'evidence-context-highlight':'clicked-match-highlight'):null;if(target)requestAnimationFrame(()=>target.scrollIntoView({behavior:'smooth',block:'center'}))}
  }catch(e){if(e.name==='AbortError'||sequence!==contextSequence)return;const fallback=clickedMatch?.snippet||'<p>The text preview could not be loaded. The original PDF remains available.</p>';detail.innerHTML=`<div class="context-shell"><header class="context-header"><div class="result-meta">Text preview</div><h2>${escapeHtml(clickedMatch?.title||'Library text')}</h2></header><div class="context-page"><div class="page-text clicked-match-highlight">${fallback}</div></div></div>`}
}
function snippetPassages(snippet){const box=document.createElement('div');box.innerHTML=snippet||'';box.querySelectorAll('.comment').forEach(node=>node.remove());const text=(box.textContent||'').replace(/Note:\s.*$/is,'').replace(/\s+/g,' ').trim(),passages=[];text.split(/(?:…|\.\.\.)/).forEach(part=>{part=part.trim();if(part.length>280){const sentences=part.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[part];sentences.map(x=>x.trim()).filter(x=>x.length>12).forEach(x=>passages.push(x))}else if(part.length>1)passages.push(part)});return passages}
function snippetAnchor(snippet){return snippetPassages(snippet).join(' ').trim()}
function evidenceReaderAnchors(text){text=String(text||'').replace(/\s+/g,' ').trim().replace(/^\d{1,4}\s+(?=\(\d+\)|[A-ZÀ-Ž])/u,'');if(!text)return[];const sentences=text.match(/[^.!?;]+[.!?;]+|[^.!?;]+$/g)||[text],anchors=[];sentences.forEach(sentence=>{sentence=sentence.trim();while(sentence.length>260){let split=sentence.lastIndexOf(' ',260);if(split<100)split=260;anchors.push(sentence.slice(0,split).trim());sentence=sentence.slice(split).trim()}if(sentence.length>12)anchors.push(sentence)});return anchors}
function readerText(value){return highlightContext(value,resultState.query,resultState.exact)}
function formattedPage(text,pageNumber){
  const lines=String(text||'').replace(/\r/g,'').split('\n').map(x=>x.trim()),blocks=[];let paragraph=[];
  const flush=()=>{if(paragraph.length){let value='';paragraph.forEach(line=>{if(value.endsWith('-')&&/^\p{Ll}/u.test(line))value=value.slice(0,-1)+line;else value+=(value?' ':'')+line});if(value)blocks.push({type:'p',text:value});paragraph=[]}};
  const heading=line=>line.length<125&&(/^(abstract|introduction|background|methods?|methodology|results?|discussion|conclusions?|references|bibliography|appendix|chapter|section|article)\b/i.test(line)||/^\d+(?:\.\d+){0,3}\.?\s+[A-ZÀ-Ž]/.test(line)||(line.length>4&&line===line.toUpperCase()&&/[A-ZÀ-Ž]/.test(line)));
  lines.forEach((line,index)=>{if(!line){flush();return}if(index===0&&pageNumber>1&&line.length<100){flush();blocks.push({type:'running',text:line});return}if(heading(line)){flush();blocks.push({type:line.length<70?'h2':'h3',text:line});return}const list=line.match(/^(?:[-•–—]|\d+[.)]|[a-z][.)])\s+(.+)/i);if(list){flush();blocks.push({type:'li',text:list[1]});return}paragraph.push(line);if(/[.!?][”’"')\]]?$/.test(line)||paragraph.join(' ').length>650)flush()});flush();
  let html='',list=[];const flushList=()=>{if(list.length){html+='<ul>'+list.map(x=>`<li>${readerText(x,pageNumber)}</li>`).join('')+'</ul>';list=[]}};
  blocks.forEach(block=>{if(block.type==='li'){list.push(block.text);return}flushList();const value=readerText(block.text,pageNumber);if(block.type==='h2')html+=`<h2>${value}</h2>`;else if(block.type==='h3')html+=`<h3>${value}</h3>`;else if(block.type==='running')html+=`<div class="reader-running-header">${value}</div>`;else html+=`<p>${value}</p>`});flushList();return html||'<div class="reader-empty">No extractable text on this page.</div>'
}
function formattedCleanBlocks(blocks=[]){
  let html='',list=[];const flushList=()=>{if(list.length){html+='<ul>'+list.map(value=>`<li>${readerText(value)}</li>`).join('')+'</ul>';list=[]}};
  blocks.forEach(block=>{const type=block.block_type||'paragraph',text=block.text||'';if(!text)return;if(type==='list_item'){list.push(text);return}flushList();const value=readerText(text);if(type==='heading')html+=`<h2>${value}</h2>`;else if(type==='footnote')html+=`<p class="reader-footnote">${value}</p>`;else if(type==='table_row')html+=`<div class="reader-table-row">${value}</div>`;else if(type==='toc_entry')html+=`<div class="reader-toc-entry">${value}</div>`;else if(type==='metadata')html+=`<div class="reader-metadata">${value}</div>`;else html+=`<p>${value}</p>`});flushList();return html||'<div class="reader-empty">No separate text block begins on this page.</div>'
}
async function startDocumentReader(attachmentId,hitPage,clickedMatch,evidenceText=''){
  const matchedPage=Math.max(1,hitPage||1),windowStart=Math.max(1,matchedPage-4);
  const exactEvidence=evidenceText||clickedMatch?._evidence_text||'',annotationSource=['annotation','embedded_annotation'].includes(clickedMatch?.kind),annotationEvidence=annotationSource?(exactEvidence||snippetAnchor(clickedMatch?.snippet||'')):'';readerState={attachmentId,hitPage:matchedPage,initialStart:windowStart,firstLoaded:0,lastLoaded:0,total:0,loadingNext:false,loadingPrev:false,finishedNext:false,finishedPrev:windowStart===1,anchors:exactEvidence?evidenceReaderAnchors(exactEvidence):snippetPassages(clickedMatch?.snippet||''),annotationEvidence,highlightClass:exactEvidence||annotationSource?'evidence-context-highlight':'clicked-match-highlight',targetPlaced:false,targetCentered:false,readyForScroll:false,version:0};
  $('#reader-from-start').onclick=()=>resetDocumentReader(1);$('#reader-back-match').onclick=()=>resetDocumentReader(Math.max(1,readerState.hitPage-4));
  const scroller=$('#context-dialog .context-page');scroller.onscroll=()=>{if(!readerState?.readyForScroll)return;const pages=$('#document-pages');if(!pages)return;const topDistance=pages.getBoundingClientRect().top-scroller.getBoundingClientRect().top;if(topDistance>-650)loadDocumentChunk('prev');if(scroller.scrollTop+scroller.clientHeight>=scroller.scrollHeight-700)loadDocumentChunk('next')};await loadDocumentChunk('next')
}
async function resetDocumentReader(start){
  if(!readerState)return;readerState.version++;readerState.initialStart=Math.max(1,start);readerState.firstLoaded=0;readerState.lastLoaded=0;readerState.loadingNext=false;readerState.loadingPrev=false;readerState.finishedNext=false;readerState.finishedPrev=start<=1;readerState.targetPlaced=false;readerState.targetCentered=false;readerState.readyForScroll=false;$('#document-pages').innerHTML='';$('#reader-load-prev').innerHTML='';$('#reader-load').innerHTML='<span class="load-spinner"></span> Loading pages…';await loadDocumentChunk('next');const scroller=$('#context-dialog .context-page'),reader=$('.document-reader');if(scroller&&reader&&!readerState.targetCentered){scroller.scrollTo({top:reader.offsetTop-18,behavior:'smooth'});readerState.readyForScroll=true}
}
function readerArticle(page){const article=document.createElement('article');article.className='reader-page';article.dataset.page=page.page_number;const clean=Array.isArray(page.blocks),content=clean?formattedCleanBlocks(page.blocks):formattedPage(page.text,page.page_number),last=clean&&page.blocks.length?Math.max(...page.blocks.map(block=>Number(block.page_end)||page.page_number)):page.page_number,label=last>page.page_number?`Pages ${page.page_number}–${last}`:`Page ${page.page_number}`;article.classList.toggle('clean-reader-page',clean);article.innerHTML=`<span class="reader-page-number">${label}</span><div class="reader-content">${content}</div>`;return article}
function canonicalPassage(raw,mapping=[]){let text='',map=[];const letter=value=>/\p{L}/u.test(value||''),alnum=value=>/[\p{L}\p{N}]/u.test(value||'');for(let i=0;i<raw.length;i++){let char=raw[i];if(char==='\u00ad')continue;if(/[-‐‑]/.test(char)&&letter(raw[i-1])){let next=i+1;while(next<raw.length&&/\s/u.test(raw[next]))next++;if(next>i+1&&letter(raw[next])){i=next-1;continue}}char=char.normalize('NFKC').toLocaleLowerCase();for(const part of char){const space=!alnum(part);if(space&&(!text||text.endsWith(' ')))continue;text+=space?' ':part;map.push(mapping[i]||null)}}return{text:text.trim(),map}}
function passageDomSource(root){const raw=[],mapping=[],blocks=new Set(['P','LI','H2','H3','DIV']);const addSpace=()=>{raw.push(' ');mapping.push(null)};const walk=node=>{if(node.nodeType===Node.TEXT_NODE){const value=node.nodeValue||'';for(let i=0;i<value.length;i++){mapping.push({node,start:i,end:i+1,order:raw.length});raw.push(value[i])}return}if(node.nodeType===Node.ELEMENT_NODE&&node.matches('.reader-page-number'))return;const block=node.nodeType===Node.ELEMENT_NODE&&blocks.has(node.tagName);if(block)addSpace();[...(node.childNodes||[])].forEach(walk);if(block)addSpace()};walk(root);return{...canonicalPassage(raw,mapping),rawMap:mapping}}
function placeExactPassages(page,anchors,highlightClass='clicked-match-highlight'){const content=page.matches?.('.reader-content,.document-pages')?page:page.querySelector('.reader-content');if(!content||!anchors.length)return null;const source=passageDomSource(content),intervals=[];let cursor=0;anchors.forEach(anchor=>{const needle=canonicalPassage([...anchor]).text;if(!needle)return;let start=source.text.indexOf(needle,cursor);if(start<0)start=source.text.indexOf(needle);if(start>=0){intervals.push([start,start+needle.length]);cursor=start+needle.length}});if(!intervals.length)return null;const byNode=new Map();intervals.forEach(([start,end])=>{const matched=source.map.slice(start,end).filter(Boolean);if(!matched.length)return;const rawStart=matched[0].order,rawEnd=matched[matched.length-1].order;source.rawMap.forEach(point=>{if(!point||point.order<rawStart||point.order>rawEnd)return;const ranges=byNode.get(point.node)||[],last=ranges.length?ranges[ranges.length-1]:null;if(last&&point.start<=last.end)last.end=Math.max(last.end,point.end);else ranges.push({start:point.start,end:point.end});byNode.set(point.node,ranges)})});const wrappers=[];[...byNode.entries()].reverse().forEach(([node,ranges])=>ranges.slice().reverse().forEach(part=>{if(part.end<=part.start)return;const range=document.createRange(),span=document.createElement('span');span.className=highlightClass;range.setStart(node,part.start);range.setEnd(node,part.end);range.surroundContents(span);wrappers.push(span)}));wrappers.sort((a,b)=>a===b?0:a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1);const target=wrappers[Math.floor(wrappers.length/2)]||null;if(target)target.id='clicked-match-target';return target}
function placeAnnotationEvidence(state){if(!state.annotationEvidence)return null;const page=$(`#document-pages .reader-page[data-page="${state.hitPage}"]`),content=page?.querySelector('.reader-content');if(!content)return null;let target=content.querySelector('.annotation-context-evidence');if(!target){target=document.createElement('p');target.className='annotation-context-evidence evidence-context-highlight';target.textContent=state.annotationEvidence;content.prepend(target)}target.id='clicked-match-target';return target}
function ensureClickedTarget(state){
  let target=$('#clicked-match-target');if(!target){const pages=$('#document-pages');if(!pages||!pages.querySelector(`.reader-page[data-page="${state.hitPage}"]`))return null;target=placeExactPassages(pages,state.anchors,state.highlightClass)||placeAnnotationEvidence(state);state.targetPlaced=!!target}
  if(target&&!state.targetCentered){state.targetCentered=true;requestAnimationFrame(()=>{target.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{if(readerState===state)state.readyForScroll=true},700)})}return target
}
function updateReaderStatus(state){const progress=$('#reader-progress'),previous=$('#reader-load-prev'),next=$('#reader-load');if(progress)progress.textContent=state.total&&state.firstLoaded?`Pages ${state.firstLoaded}–${state.lastLoaded} of ${state.total}`:'No extracted pages';if(previous)previous.innerHTML=state.finishedPrev?'':'<span class="load-spinner"></span> Scroll up to load earlier pages';if(next)next.innerHTML=state.finishedNext?'<div class="reader-end">End of extracted document</div>':'<span class="load-spinner"></span> Scroll to load later pages'}
async function loadDocumentChunk(direction='next'){
  const state=readerState;if(!state)return;const previous=direction==='prev';if(previous&&(state.loadingPrev||state.finishedPrev||!state.firstLoaded))return;if(!previous&&(state.loadingNext||state.finishedNext))return;const start=previous?Math.max(1,state.firstLoaded-10):(state.lastLoaded?state.lastLoaded+1:state.initialStart),limit=previous?state.firstLoaded-start:10;if(limit<1)return;const version=state.version;state[previous?'loadingPrev':'loadingNext']=true;const loader=$(previous?'#reader-load-prev':'#reader-load');if(loader)loader.innerHTML='<span class="load-spinner"></span> Loading pages…';
  try{const data=await fetch(`/api/document-pages?attachment_id=${state.attachmentId}&start=${start}&limit=${limit}`).then(r=>r.json());if(readerState!==state||version!==state.version)return;state.total=data.total_pages||0;const box=$('#document-pages'),scroller=$('#context-dialog .context-page'),oldHeight=scroller?.scrollHeight||0,oldTop=scroller?.scrollTop||0,pages=data.pages||[],fragment=document.createDocumentFragment();pages.forEach(page=>fragment.appendChild(readerArticle(page)));if(previous)box.prepend(fragment);else box.appendChild(fragment);if(pages.length){const first=pages[0].page_number,last=pages[pages.length-1].page_number;state.firstLoaded=state.firstLoaded?Math.min(state.firstLoaded,first):first;state.lastLoaded=Math.max(state.lastLoaded,last);if(previous&&scroller)scroller.scrollTop=oldTop+(scroller.scrollHeight-oldHeight)}state.finishedPrev=state.firstLoaded<=1||(previous&&!pages.length);state.finishedNext=state.total?state.lastLoaded>=state.total:(!data.has_more||!pages.length);state[previous?'loadingPrev':'loadingNext']=false;const target=ensureClickedTarget(state);if(!target)state.readyForScroll=true;updateReaderStatus(state);if(!previous&&!state.finishedNext&&scroller&&scroller.scrollHeight<=scroller.clientHeight+800)loadDocumentChunk('next')}catch(e){state[previous?'loadingPrev':'loadingNext']=false;if(loader)loader.textContent=previous?'Earlier pages could not be loaded.':'Later pages could not be loaded.'}
}
async function toggleGroup(key,itemId,obsidianNoteId,button){if(expandedGroups.has(key)){expandedGroups.delete(key);render(resultState.results,resultState.query);return}expandedGroups.add(key);if(resultState.query&&(itemId||obsidianNoteId)&&!publicationMatches.has(key)){button.innerHTML='<span class="load-spinner"></span> Loading all matches';button.disabled=true;try{const extra=filterParams(resultState.filters),source=obsidianNoteId?`obsidian_note_id=${encodeURIComponent(obsidianNoteId)}`:`item_id=${itemId}`,url=`/api/search/publication?q=${encodeURIComponent(resultState.query)}&scope=${resultState.scope}&exact=${resultState.exact?1:0}&${source}${extra?'&'+extra:''}`;const data=await fetch(url).then(r=>r.json());publicationMatches.set(key,data.results||[])}catch(e){publicationMatches.set(key,grouped(resultState.results).find(g=>g.key===key)?.matches||[])}}render(resultState.results,resultState.query)}
async function showAuthor(name){if(!historySourceCurrent)return staleHistoryNotice();if(activeRequest)activeRequest.abort();expandedGroups.clear();publicationMatches.clear();resultState={query:'',scope:'metadata',exact:false,results:[],hasMore:false,loading:false};$('#welcome').classList.add('hidden');$('#answer').classList.add('hidden');$('#results').innerHTML='<div class="empty">Loading this author’s papers...</div>';const data=await fetch('/api/author?name='+encodeURIComponent(name)).then(r=>r.json());resultState.results=data.results||[];render(resultState.results,name,`Papers by ${name}`);window.scrollTo({top:0,behavior:'smooth'})}
async function loadMore(){if(!resultState.hasMore||resultState.loading||resultState.fromHistory)return;resultState.loading=true;const footer=$('#load-more');if(footer)footer.innerHTML='<span class="load-spinner"></span>Loading more matches...';try{const extra=filterParams(resultState.filters),response=await fetch(`/api/search?q=${encodeURIComponent(resultState.query)}&scope=${resultState.scope}&method=${resultState.method||'hybrid'}&embedding_model=${encodeURIComponent(resultState.embeddingModel||'qwen3-embedding:0.6b')}&exact=${resultState.exact?1:0}&generate_answer=0&offset=${resultState.results.length}${extra?'&'+extra:''}`);if(!response.ok)throw new Error('Load failed');const data=await response.json();resultState.results.push(...data.results);resultState.hasMore=data.has_more;resultState.loading=false;render(resultState.results,resultState.query);await saveHistorySnapshot()}catch(e){resultState.loading=false;if(footer)footer.textContent='Could not load more results. Scroll to retry.'}}
window.addEventListener('scroll',()=>{if(window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-500)loadMore()},{passive:true});
async function showItem(id){if(!historySourceCurrent)return staleHistoryNotice();const i=await fetch('/api/item/'+id).then(r=>r.json());let creators=[];try{creators=JSON.parse(i.creators_json||'[]')}catch{}const authors=creators.map(c=>[c.firstName,c.lastName].filter(Boolean).join(' ')).join(', ');$('#item-detail').innerHTML=`<div class="result-meta">${escapeHtml(i.item_type||'Library item')}</div><h2 class="detail-title">${escapeHtml(i.title||'Untitled')}</h2><p class="detail-meta">${escapeHtml(authors)}${i.date_created?' · '+escapeHtml(i.date_created):''}</p><h3>Attachments</h3>${(i.attachments||[]).map(a=>`<div class="attachment"><span>${escapeHtml(a.title||a.content_type||'Attachment')} · ${a.annotation_count} annotations</span>${a.local_path?`<a href="/api/file/${a.id}" target="_blank">Open</a>`:'<small>File unavailable</small>'}</div>`).join('')}`;$('#item-dialog').showModal()}
function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function legacyEntries(){try{const cutoff=Date.now()-180*86400000,all=JSON.parse(localStorage.getItem('marginalia-recent-searches')||'[]'),kept=(Array.isArray(all)?all:[]).filter(entry=>!entry.time||new Date(entry.time).getTime()>=cutoff).sort((a,b)=>new Date(b.time||0)-new Date(a.time||0)).slice(0,100);if(kept.length!==all.length)localStorage.setItem('marginalia-recent-searches',JSON.stringify(kept));return kept}catch{return[]}}
function historySnapshot(){return{query:resultState.query,scope:resultState.scope,method:resultState.method,embedding_model:resultState.embeddingModel,answer_model:resultState.answerModel||answerModel,exact:!!resultState.exact,generate_answer:!!resultState.generateAnswer,answer_mode:resultState.answerMode||answerMode(),filters:resultState.filters||{},results:resultState.results||[],has_more:!!resultState.hasMore,answer:currentAnswerText,answer_sources:answerSources,answer_evidence:answerEvidence,evidence_status:resultState.evidenceStatus||null,retrieval_seconds:resultState.retrievalSeconds??null,answer_seconds:resultState.answerSeconds??null,answer_metrics:currentAnswerMetrics}}
async function saveHistorySnapshot(){if(!resultState.query||resultState.fromHistory)return;try{const response=await fetch('/api/history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:currentHistoryId,snapshot:historySnapshot()})});if(!response.ok)return;const data=await response.json();currentHistoryId=data.id;await refreshHistory()}catch{}}
async function refreshHistory(){try{const data=await fetch('/api/history').then(r=>r.json());historyEntries=data.history||[]}catch{historyEntries=[]}renderRecent()}
function renderRecent(){const legacy=legacyEntries().map((entry,index)=>({...entry,_legacy:true,_legacyIndex:index,updated_at:entry.time})),items=[...historyEntries,...legacy],box=$('#recent-searches');if(!box)return;if(!items.length){box.innerHTML='<div class="recent-empty">Your completed searches will appear here.</div>';$('#clear-recent').hidden=true;return}$('#clear-recent').hidden=false;box.innerHTML=items.map((x,i)=>{const method=x.method||'hybrid',model=x.embedding_model||'qwen3-embedding:0.6b',answer=!!(x.generate_answer??x.mode==='ask'),generator=x.answer_model||'gemma4:12b',date=x.updated_at||x.time;return `<div class="recent-search-row"><button class="recent-search" data-recent="${i}"><span class="recent-icon">${answer?'✦':'⌕'}</span><span><strong class="recent-query">${escapeHtml(x.query)}</strong><span class="recent-meta"><span class="${x._legacy?'recent-legacy':'recent-cache'}">${x._legacy?'Run again · old entry':'Saved result'}</span><span>${escapeHtml(labels[x.scope]||x.scope)}</span><span>${escapeHtml(retrievalLabels[method]||method)}</span>${method!=='bm25'?`<span>${escapeHtml(embeddingLabels[model]||model)}</span>`:''}${!x._legacy?`<span>${x.result_count} matches</span>`:''}${answer?`<span>${escapeHtml(generator)} · ${(x.answer_mode||'fast')==='full'?'full':'fast'}</span>`:''}</span></span><time class="recent-time">${new Date(date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time></button><button class="recent-remove" data-remove-recent="${i}" aria-label="Remove ${escapeHtml(x.query)} from history" title="Remove from history">×</button></div>`}).join('');$$('.recent-search').forEach(button=>button.onclick=()=>{const entry=items[Number(button.dataset.recent)];entry._legacy?repeatLegacy(entry):restoreHistory(entry.id)});$$('.recent-remove').forEach(button=>button.onclick=()=>removeHistoryEntry(items[Number(button.dataset.removeRecent)]))}
async function removeHistoryEntry(entry){if(entry._legacy){const legacy=legacyEntries();legacy.splice(entry._legacyIndex,1);localStorage.setItem('marginalia-recent-searches',JSON.stringify(legacy));renderRecent();return}try{const response=await fetch('/api/history/'+encodeURIComponent(entry.id),{method:'DELETE'});if(!response.ok)throw new Error('Delete failed');await refreshHistory()}catch{}}
function applyHistorySettings(entry){if(Object.hasOwn(entry,'_source_current'))historySourceCurrent=!!entry._source_current;scope=entry.scope||'all';retrievalMethod=entry.method||'hybrid';embeddingModel=entry.embedding_model||'qwen3-embedding:0.6b';answerModel=entry.answer_model||'gemma4:12b';$('#query').value=entry.query;$('#exact-match').checked=!!entry.exact;$('#embedding-model').value=embeddingModel;$('#answer-model').value=answerModel;$('#generate-answer').checked=!!(entry.generate_answer??entry.mode==='ask');$('#answer-mode').value=entry.answer_mode==='full'?'full':'fast';syncRetrievalControls();syncAnswerMode();setFilters(entry.filters||{});$('#scope-label').textContent=labels[scope];$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.scope===scope))}
function repeatLegacy(entry){applyHistorySettings(entry);run()}
function showSavedTimings(snapshot){const search=$('#search-progress'),retrieval=$('#retrieval-progress'),answer=$('#answer-progress');search.classList.remove('hidden');retrieval.classList.remove('hidden');$('#progress-bar').style.width='100%';$('#progress-bar').className='progress-bar done';$('#progress-label').textContent='Saved search results';$('#progress-time').textContent=snapshot.retrieval_seconds==null?'—':Number(snapshot.retrieval_seconds).toFixed(1)+'s';if(snapshot.generate_answer&&snapshot.answer){answer.classList.remove('hidden');$('#answer-progress-bar').style.width='100%';$('#answer-progress-bar').className='progress-bar answer-progress-bar done';$('#answer-progress-label').textContent='Saved model answer';$('#answer-progress-time').textContent=snapshot.answer_seconds==null?'—':Number(snapshot.answer_seconds).toFixed(1)+'s'}else answer.classList.add('hidden')}
async function restoreHistory(id){if(activeRequest)activeRequest.abort();try{const data=await fetch('/api/history/'+encodeURIComponent(id)).then(r=>{if(!r.ok)throw new Error('Saved result is unavailable');return r.json()}),snapshot=data.snapshot;applyHistorySettings(snapshot);currentHistoryId=id;currentAnswerText=snapshot.answer||'';currentAnswerMetrics=snapshot.answer_metrics||null;answerSources=snapshot.answer_sources||[];answerEvidence=snapshot.answer_evidence||[];expandedGroups.clear();publicationMatches.clear();resultState={query:snapshot.query,scope:snapshot.scope,method:snapshot.method,embeddingModel:snapshot.embedding_model,answerModel:snapshot.answer_model,answerMode:snapshot.answer_mode,exact:!!snapshot.exact,generateAnswer:!!snapshot.generate_answer,filters:snapshot.filters||{},results:snapshot.results||[],hasMore:false,loading:false,fromHistory:true,evidenceStatus:snapshot.evidence_status||null,retrievalSeconds:snapshot.retrieval_seconds,answerSeconds:snapshot.answer_seconds};$('#welcome').classList.add('hidden');showSavedTimings(snapshot);render(resultState.results,resultState.query);const notice=$('#history-notice');notice.classList.remove('hidden');notice.innerHTML=`<span>Saved snapshot · no search or model generation was run</span><button id="history-search-again">Search again</button>`;$('#history-search-again').onclick=()=>run();const box=$('#answer');if(currentAnswerText){box.classList.remove('hidden');box.innerHTML=`<div class="answer-heading"><h2>Answer from your library</h2><span>Saved · ${escapeHtml(snapshot.answer_model||'local model')} · ${snapshot.answer_mode==='full'?'Full answer':'Fast answer'}</span></div><div class="answer-text">${answerMarkup(currentAnswerText)}</div>`;bindAnswerCitations(box)}else box.classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})}catch(e){alert(e.message||'The saved result could not be opened.')}}
$('#clear-recent').onclick=async()=>{localStorage.removeItem('marginalia-recent-searches');try{await fetch('/api/history',{method:'DELETE'})}catch{}await refreshHistory()};
refreshHistory();

// Standalone onboarding and explicit, user-triggered refresh.
let productStatus=null,refreshPoll=null,refreshPolling=false,refreshStartedAt=0,refreshNeedsReload=false,refreshDisplayedPercent=2,aiManagerPoll=null,aiManagerPolling=false,aiRefreshState=null;
async function productRequest(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error([data.error,data.detail].filter(Boolean).join(' · ')||'Request failed');return data}
function showSetup(status=productStatus){const overlay=$('#setup-overlay');$('#setup-zotero').value=status?.zotero_path||'';$('#setup-linked').value=status?.linked_attachment_base_path||'';$('#setup-obsidian').value=status?.obsidian_path||'';overlay.classList.remove('hidden');$('#setup-title').textContent=status?.configured?'Source folders':'Connect your libraries';$('#setup-start').textContent=status?.configured?'Save and refresh private copies':'Copy and build my library'}
function setupError(message=''){const box=$('#setup-error');box.textContent=message;box.classList.toggle('hidden',!message)}
async function initializeProduct(){try{productStatus=await productRequest('/api/setup/status');if(!productStatus.configured||!productStatus.library_ready)showSetup(productStatus);if(productStatus.refresh?.running||productStatus.refresh?.phase==='failed')showRefresh(productStatus.refresh)}catch(error){setupError(error.message);showSetup({})}}
$$('[data-pick-folder]').forEach(button=>button.onclick=async()=>{const kind=button.dataset.pickFolder;button.disabled=true;setupError();try{const data=await productRequest('/api/setup/pick-folder?kind='+kind);if(data.path)$(`#setup-${kind}`).value=data.path}catch(error){setupError(error.message)}finally{button.disabled=false}});
$('#clear-obsidian').onclick=()=>{$('#setup-obsidian').value=''};
$('#clear-zotero').onclick=()=>{$('#setup-zotero').value=''};
$('#clear-linked').onclick=()=>{$('#setup-linked').value=''};
$('#library-settings').onclick=async()=>{try{productStatus=await productRequest('/api/setup/status')}catch{}showSetup(productStatus||{})};
$('#setup-start').onclick=async()=>{
  const button=$('#setup-start'),zotero=$('#setup-zotero').value.trim(),linked=$('#setup-linked').value.trim(),obsidian=$('#setup-obsidian').value.trim(),same=(left,right)=>String(left||'').trim().toLocaleLowerCase()===String(right||'').trim().toLocaleLowerCase(),replaced=[];
  if(productStatus?.zotero_path&&!same(productStatus.zotero_path,zotero))replaced.push('Zotero');
  if(productStatus?.obsidian_path&&!same(productStatus.obsidian_path,obsidian))replaced.push('Obsidian');
  if(replaced.length&&!confirm(`You are replacing or removing the previous ${replaced.join(' and ')} source.\n\nThe new refresh will atomically replace its searchable library and private source copy. Saved search history can still contain old text until you use “Clear all history”. If semantic indexing cannot finish, reusable embedding records may remain until a later successful refresh.\n\nContinue with the source change?`))return;
  button.disabled=true;setupError();try{await productRequest('/api/setup/configure',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({zotero_path:zotero,linked_attachment_base_path:linked,obsidian_path:obsidian,start_refresh:true})});$('#setup-overlay').classList.add('hidden');showRefresh()}catch(error){setupError(error.message)}finally{button.disabled=false}
};
$('#refresh-library').onclick=async()=>{try{const data=await productRequest('/api/refresh/start',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});showRefresh(data.refresh)}catch(error){if(/already|running/i.test(error.message))showRefresh();else alert(error.message)}};
function showRefresh(initial=null){const dialog=$('#refresh-dialog');refreshStartedAt=Date.now();refreshNeedsReload=false;refreshDisplayedPercent=2;if(!dialog.open)dialog.showModal();$('#refresh-close').classList.add('hidden');updateRefresh(initial);clearInterval(refreshPoll);refreshPoll=setInterval(pollRefresh,700);pollRefresh()}
async function pollRefresh(){if(refreshPolling)return;refreshPolling=true;try{updateRefresh(await productRequest('/api/refresh/status'))}catch(error){$('#refresh-message').textContent=error.message}finally{refreshPolling=false}}
function refreshActivityEntry(value){return typeof value==='string'?{message:value,at:0}:{message:value?.message||'Working…',at:Number(value?.at)||0}}
function renderRefreshActivity(state){
  const modelProgress=state.semantic_model_total?`Model ${state.semantic_model_current} of ${state.semantic_model_total} · ${state.semantic_model}`:'',current=[modelProgress,state.activity||'Working…'].filter(Boolean).join(' · '),history=(Array.isArray(state.activity_log)?state.activity_log:[]).map(refreshActivityEntry),list=$('#refresh-activity-log'),detailCurrent=Math.max(0,Number(state.detail_current)||0),detailTotal=Math.max(0,Number(state.detail_total)||0),eta=String(state.detail_eta||'').trim();
  $('#refresh-activity').textContent=current;$('#refresh-detail').textContent=detailTotal?`${detailCurrent.toLocaleString()} of ${detailTotal.toLocaleString()} · ${Math.round(100*Math.min(1,detailCurrent/detailTotal))}%${eta?' · ETA '+eta:''}`:'';
  const runtime=$('#refresh-runtime'),device=String(state.semantic_device||'').toUpperCase(),runtimeLabels={GPU:'Embedding: GPU',CPU:'Embedding: CPU',DETECTING:'Embedding device: detecting…',UNKNOWN:'Embedding device: unknown'};runtime.textContent=runtimeLabels[device]||'';runtime.className='refresh-runtime'+(device?' '+device.toLowerCase():'');runtime.title=String(state.semantic_runtime_detail||'');
  const previous=history.slice(0,-1).slice(-10);list.replaceChildren(...previous.map(entry=>{const item=document.createElement('li'),clock=document.createElement('time'),message=document.createElement('span');clock.textContent=entry.at?new Date(entry.at*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'';message.textContent=entry.message;item.append(clock,message);return item}));list.scrollTop=list.scrollHeight
}
function renderRefreshStages(state,current,total){const labels=Array.isArray(state.stage_labels)?state.stage_labels:[],list=$('#refresh-stage-list'),active=state.phase==='complete'?total+1:current;list.replaceChildren(...labels.map((label,index)=>{const item=document.createElement('li');item.textContent=`${index+1}. ${label}`;item.className=index+1<active?'completed':index+1===active?'current':'';return item}));if(!labels.length)list.textContent=`Step ${current} of ${total}`}
function updateRefresh(state){if(!state)return;const total=Math.max(1,Number(state.total)||1),current=Math.max(1,Number(state.current)||1),detailCurrent=Math.max(0,Number(state.detail_current)||0),detailTotal=Math.max(0,Number(state.detail_total)||0),fraction=detailTotal?Math.min(1,detailCurrent/detailTotal):0,done=!state.running&&['complete','failed'].includes(state.phase),rawPercent=state.phase==='complete'?100:Math.max(2,Math.min(96,100*((current-1)+fraction)/total));refreshDisplayedPercent=state.phase==='complete'?100:Math.max(refreshDisplayedPercent,rawPercent);const percent=refreshDisplayedPercent;$('#refresh-bar').style.width=percent+'%';$('#refresh-message').textContent=state.error||state.message||'Working…';renderRefreshActivity(state);renderRefreshStages(state,current,total);const sourceWarning=$('#source-lock-warning');$('#source-lock-message').textContent=state.source_warning||'';sourceWarning.classList.toggle('hidden',!state.source_blocked);$('#refresh-step').textContent=state.phase==='complete'?'Complete':state.phase==='failed'?'Stopped':`Step ${Math.min(current,total)} of ${total} · overall ${Math.round(percent)}%`;const now=Date.now()/1000,elapsed=state.started_at?Math.max(0,now-state.started_at):(Date.now()-refreshStartedAt)/1000,stageElapsed=state.stage_started_at?Math.max(0,now-state.stage_started_at):elapsed;$('#refresh-time').textContent=Math.round(elapsed)+'s total';$('#refresh-stage-time').textContent=Math.round(stageElapsed)+'s this stage';$('#refresh-title').textContent=state.phase==='complete'?'Your library is ready':state.phase==='failed'?'Refresh needs attention':'Refreshing private library copies';const warning=$('#refresh-warning'),messages=state.warnings||[];warning.textContent=messages.join('\n');warning.classList.toggle('hidden',!messages.length);if(done){clearInterval(refreshPoll);refreshPoll=null;$('#refresh-close').classList.remove('hidden');refreshNeedsReload=state.phase==='complete'}}
function renderAiSetup(state){const panel=$('#ai-setup'),visible=state?.phase==='ai_setup'&&state?.ai_setup_required;panel.classList.toggle('hidden',!visible);if(!visible)return;const installed=!!llmState?.installed,install=llmState?.model_install||{},percent=install.total?Math.round(100*install.completed/install.total):0;$('#ai-get-ollama').classList.toggle('hidden',installed);$('#ai-install-qwen').disabled=!installed||install.running;$('#ai-install-gemma').disabled=!installed||install.running;$('#ai-install-custom').disabled=!installed||install.running;$('#ai-install-custom-embedding').disabled=!installed||install.running;$('#ai-setup-status').textContent=install.running?`${install.status||'Downloading'}${percent?' · '+percent+'%':''}`:install.status==='failed'?(install.error||'Download failed'):!installed?'Install Ollama, then return here. Marginalia will detect it automatically.':''}
const originalUpdateRefresh=updateRefresh;updateRefresh=state=>{originalUpdateRefresh(state);renderAiSetup(state)};
function renderCustomEmbeddingModels(){const box=$('#custom-embedding-models'),custom=(llmState?.embedding_models||[]).filter(item=>!['qwen3-embedding:0.6b','qwen3-embedding:8b'].includes(item.model));box.innerHTML=custom.map(item=>`<div><strong>${escapeHtml(item.model)}</strong><small>User-selected embedding model · independent semantic index</small><button data-install-embedding="${escapeHtml(item.model)}">Install</button><button class="remove-custom-model" data-remove-embedding="${escapeHtml(item.model)}">Remove index</button></div>`).join('');box.querySelectorAll('[data-install-embedding]').forEach(bindEmbeddingButton);box.querySelectorAll('[data-remove-embedding]').forEach(button=>button.onclick=async()=>{if(!confirm(`Remove Marginalia's index for ${button.dataset.removeEmbedding}? The Ollama model itself will be kept.`))return;try{await productRequest('/api/ai/model?model='+encodeURIComponent(button.dataset.removeEmbedding),{method:'DELETE'});await refreshLlmState();renderAiManager()}catch(error){$('#ai-manager-status').textContent=error.message}})}
function renderAiManager(){const dialog=$('#ai-models-dialog');if(!dialog.open)return;renderCustomEmbeddingModels();const install=llmState?.model_install||{},downloadPercent=install.total?Math.round(100*install.completed/install.total):0,semanticRunning=!!aiRefreshState?.running&&aiRefreshState.phase==='semantic',detailCurrent=Number(aiRefreshState?.detail_current)||0,detailTotal=Number(aiRefreshState?.detail_total)||0,indexPercent=detailTotal?Math.round(100*detailCurrent/detailTotal):0,installedAnswers=new Set((llmState?.answer_models||[]).map(item=>item.model));$$('[data-install-embedding]').forEach(button=>{const choice=(llmState?.embedding_models||[]).find(item=>item.model===button.dataset.installEmbedding),installed=!!choice?.installed,ready=!!choice?.semantic_index?.ready;button.textContent=ready?'Ready':installed?'Build index':'Install';button.disabled=ready||install.running||semanticRunning||!llmState?.installed;button.dataset.action=installed?'build':'install'});$$('[data-install-answer]').forEach(button=>{const installed=installedAnswers.has(button.dataset.installAnswer);button.textContent=installed?'Installed':'Install';button.disabled=installed||install.running||!llmState?.installed});const progress=$('#ai-manager-progress'),visible=install.running||install.status==='failed'||semanticRunning;progress.classList.toggle('hidden',!visible);$('#ai-manager-status').textContent=semanticRunning?(aiRefreshState.activity||'Building semantic index')+(indexPercent?' · '+indexPercent+'%':''):install.running?`${install.status||'Downloading'}${downloadPercent?' · '+downloadPercent+'%':''}`:(install.error||'');$('#ai-manager-bar').style.width=(semanticRunning?(indexPercent||4):install.running?(downloadPercent||4):0)+'%'}
async function pollAiManager(){if(!$('#ai-models-dialog').open||aiManagerPolling)return;aiManagerPolling=true;try{await refreshLlmState();try{aiRefreshState=await productRequest('/api/refresh/status')}catch{aiRefreshState=null}renderAiManager()}finally{aiManagerPolling=false}}
async function openAiModels(){await refreshLlmState();try{aiRefreshState=await productRequest('/api/refresh/status')}catch{aiRefreshState=null}const dialog=$('#ai-models-dialog');if(!dialog.open)dialog.showModal();renderAiManager();clearInterval(aiManagerPoll);aiManagerPoll=setInterval(pollAiManager,1000)}
async function startAiInstall(url,model){try{await productRequest(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model})});if(url.endsWith('install-embedding')){embeddingModel=model;localStorage.setItem('marginalia-embedding-model',model)}const poll=async()=>{await refreshLlmState();renderAiSetup({phase:'ai_setup',ai_setup_required:true});renderAiManager();if(llmState?.model_install?.running)setTimeout(poll,1000);else{try{const state=await productRequest('/api/refresh/status');if(state.running&&state.phase==='semantic')showRefresh(state)}catch{}}};poll()}catch(error){$('#ai-setup-status').textContent=error.message;$('#ai-manager-status').textContent=error.message;$('#ai-manager-progress').classList.remove('hidden')}}
function bindEmbeddingButton(button){button.onclick=async()=>{if(button.dataset.action==='build'){try{const data=await productRequest('/api/ai/build-index',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:button.dataset.installEmbedding})});aiRefreshState=data.refresh;renderAiManager()}catch(error){$('#ai-manager-status').textContent=error.message;$('#ai-manager-progress').classList.remove('hidden')}}else startAiInstall('/api/ai/install-embedding',button.dataset.installEmbedding)}}
$('#ai-get-ollama').onclick=()=>window.open('https://ollama.com/download/windows','_blank','noopener');
$('#ai-install-qwen').onclick=()=>startAiInstall('/api/ai/install-embedding','qwen3-embedding:0.6b');
$('#ai-install-gemma').onclick=()=>startAiInstall('/api/ai/install-answer','gemma4:12b');
$('#ai-install-custom-embedding').onclick=()=>{const model=$('#ai-custom-embedding').value.trim();if(model)startAiInstall('/api/ai/install-embedding',model)};
$('#ai-install-custom').onclick=()=>{const model=$('#ai-custom-model').value.trim();if(model)startAiInstall('/api/ai/install-answer',model)};
$('#ai-skip').onclick=async()=>{try{await productRequest('/api/ai/skip',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})}catch(error){$('#ai-setup-status').textContent=error.message}};
$('#ai-models').onclick=openAiModels;$('#ai-models-dialog .close').onclick=()=>$('#ai-models-dialog').close();$('#ai-models-dialog').addEventListener('close',()=>{clearInterval(aiManagerPoll);aiManagerPoll=null});
$$('[data-install-embedding]').forEach(bindEmbeddingButton);
$$('[data-install-answer]').forEach(button=>button.onclick=()=>startAiInstall('/api/ai/install-answer',button.dataset.installAnswer));
$('#ai-manager-install-custom').onclick=()=>{const model=$('#ai-manager-custom').value.trim();if(model)startAiInstall('/api/ai/install-answer',model)};
$('#ai-manager-install-custom-embedding').onclick=()=>{const model=$('#ai-manager-custom-embedding').value.trim();if(model)startAiInstall('/api/ai/install-embedding',model)};
$('#refresh-close').onclick=()=>{if(refreshNeedsReload)location.reload();else $('#refresh-dialog').close()};
initializeProduct();
